cookie:
  expiry_days: 30
  key: proj_mgmt_secret_key_change_me
  name: proj_mgmt_auth

credentials:
  usernames:
    LXS:
      email: lxs@example.com
      failed_login_attempts: 0
      first_name: LXS
      last_name: User
      logged_in: false
      password: $2b$12$9mTfT/t0du/d.yBH1gJE.e2QNohNk.TRaaBUW16.B39B2GUmxjJA2
      roles:
        - admin
